#!/usr/bin/env bash

pid=`ps aux | grep 'rg --' | grep -v 'grep' | awk '{print $2}'`
# pid=`ps aux | grep 'ruby' | grep -v 'grep' | awk '{print $2}'`
if [ $pid > 0 ]; then
  ppid=`ps -o ppid= $pid`
  echo "The rg is runnning... pid is $pid."
  echo "Parent pid of the rg is runnning... pid is $ppid."
  kill $pid
  kill $ppid
else
  echo 'Nothing the rg pid.'
fi
